---
title: "csvcombiner_PMG"
author: "Michael Soriano"
date: "11/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The creation of the combined csv file
```{r}
#Gets list of all files/csv's in the fixtures folder
filenames = list.files("fixtures", patter = "*.csv",full.names = FALSE)

#initializes combined df variable
combinedCSV = data.frame()

#for loop that iterates for each file in fixtures folder based on filenames list 
for (i in 1:length(filenames)) {
  nameCSV = filenames[i] #created variable for current csv file
  fileVar = 
    paste("./fixtures/",nameCSV, sep = "" ) #concatenates folder name with current file
  df = read.csv(file = fileVar) #reads the current csv and assigns it to a variable
  newCOL = rep_len(nameCSV,lengths(df[1])) #creates a new column that attaches the filename based on the length of the csv 
  df$filename = newCOL #attaches prev column to dataframe
  combinedCSV = rbind(combinedCSV,df) #adds current df to the combined csv variable
  }

```

Outputting CSV
```{r}
#outputs the combined csv to working directory
write.csv(combinedCSV, file = "combined.csv", row.names = FALSE) 
checkNew = read.csv(file = "combined.csv")
print(checkNew)
```
